version: "2"

services:
  app:
    image: golang:alpine
    ports:
      - "8080"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - VIRTUAL_HOST=uuid.gorzsony.com
      - VIRTUAL_PORT=8080
      - RANDOMORG_APIKEY
    command: go run -mod=vendor . -apikey "${RANDOMORG_APIKEY}"
